### PR TITLE
Adding Holidays for Egypt and United Arab Emirates

### PR DESCRIPTION
**Pull request by samymohammed**
Add relative based calculations for any chronology in CalendarUtil

### CODE REVIEW

**Comment by hakan42** [comment]
You forgot the turkish translation file...

**Comment by kguelzau** [comment]
👍 we will need this :-)

**Comment by samymohammed** [comment]
Sorry, but which file ??

Best regards,
Mohammed Samy
novomind Egypt LLC
_____________________________
7 Abou Rafea Street, Moustafa Kamel, Alexandria, Egypt
Phone +20 3 5447541 – 307
email Mohamed.samy@nm-eg.com · Skype Mohamed.samy_nmeg

**Comment by svendiedrichsen** [comment]
Thank you, @samymohammed

**Pull request merged**
