### PR TITLE
Update US Federal Calendar

### PR DESCRIPTION
**Pull request by meingraham**
Added a few missing holidays and official days on the US Federal calendar

Update - small typo corrected

### CODE REVIEW

**Comment by svendiedrichsen** [comment]
@meingraham This does not build. Could you fix it please.

**Comment by meingraham** [comment]
I do not know how to work with GitHub. I do not know how to update my PR.

I suspect that it is this entry at line 407 that is causing the problem:
```
		<tns:RelativeToWeekdayInMonth which="FIRST" weekday="TUESDAY" when="AFTER" descriptionPropertiesKey="ELECTION_DAY">
			<tns:FixedWeekday which="FIRST" weekday="MONDAY" month="NOVEMBER" />
		</tns:RelativeToWeekdayInMonth>
```

Perhaps this will build (remove "which="FIRST" ") on line 407?
```
		<tns:RelativeToWeekdayInMonth weekday="TUESDAY" when="AFTER" descriptionPropertiesKey="ELECTION_DAY">
			<tns:FixedWeekday which="FIRST" weekday="MONDAY" month="NOVEMBER" />
		</tns:RelativeToWeekdayInMonth>
```

**Comment by svendiedrichsen** [comment]
@meingraham A great opportunity to learn how to work with github then.

Github only manages your git repository. To work with it you clone your repository to your local machine. `git clone <REPO URL>`. Then you switch to your branch you have created the pull request from. `git checkout -b <BRANCH NAME>` 

You then make your changes locally and build jolly day with `mvn clean package`. When your are done commit your changes. `git commit -m "Your commit comment` After that you push your changes to your repository on github by calling `git push`. The changes will automatically get picked up and the pull request gets updated.

Have fun.
Cheers, Sven

**Comment by meingraham** [comment]
OK... let's see if I did it right... and if my syntax changes address the issue.

**Comment by svendiedrichsen** [comment]
Didn't work. If you build it locally the turnaound cycles would be shorter.

**Comment by meingraham** [comment]
Sven,

Oh well, I'm not using Jollydays at this time.

openHAB will be adding a new Ephemeris service in a few weeks (I am told) which will be able to "consume" Jollydays. For now I just wanted to contribute to this project as the US Federal Holidays are not up to date. When Ephemeris comes online, I will implement it locally on my server... and I'm not sure what if anything I'll need to build... or if I'll just consume the holidays XML files "standalone".

In any case, building this project to debug my syntax is beyond my capabilities. As such, I am withdrawing the pull request and have deleted my fork. I wish I could have successfully contributed to this great project!

Mike

**Comment by svendiedrichsen** [comment]
I'm sad to hear that you give up. Maybe you could post your changes here and I'll put some time into it.

**Comment by meingraham** [comment]
Sven,

I will probably revisit this once Ephemeris is available. For now, I'd have no way to learn how to get this deployed or in using it.

Here is the US Federal Holidays section (potentially with syntax issues):
```
  <tns:Holidays>
	  <tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
	  <tns:Fixed month="MAY" day="30" validFrom="1869" validTo="1967" descriptionPropertiesKey="MEMORIAL_DAY"/>
	  <tns:Fixed month="JUNE" day="14" validFrom="1946" descriptionPropertiesKey="FLAG_DAY"/>
	  <tns:Fixed month="JULY" day="4" validFrom="1776" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
	  <tns:Fixed month="NOVEMBER" day="11" validFrom="1938" descriptionPropertiesKey="VETERANS_DAY"/>
	  <tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
	  <tns:FixedWeekday which="THIRD" weekday="MONDAY" month="JANUARY" validFrom="1986" descriptionPropertiesKey="MARTIN_LUTHER_KING"/>
	  <tns:FixedWeekday which="THIRD" weekday="MONDAY" month="FEBRUARY" validFrom="1971" descriptionPropertiesKey="PRESIDENTS_DAY"/>
	  <tns:FixedWeekday which="LAST" weekday="MONDAY" month="MAY" validFrom="1968" descriptionPropertiesKey="MEMORIAL_DAY"/>
	  <tns:FixedWeekday which="FIRST" weekday="MONDAY" month="SEPTEMBER" validFrom="1895" descriptionPropertiesKey="LABOR_DAY"/>
	  <tns:FixedWeekday which="SECOND" weekday="MONDAY" month="OCTOBER" validFrom="1937" descriptionPropertiesKey="COLUMBUS_DAY"/>
	  <tns:RelativeToWeekdayInMonth weekday="TUESDAY" when="AFTER" descriptionPropertiesKey="ELECTION_DAY" every="EVEN_YEARS">
		  <tns:FixedWeekday which="FIRST" weekday="MONDAY" month="NOVEMBER" />
	  </tns:RelativeToWeekdayInMonth>
	  <tns:FixedWeekday which="FOURTH" weekday="THURSDAY" month="NOVEMBER" validFrom="1863" descriptionPropertiesKey="THANKSGIVING"/>
  </tns:Holidays>
```

Once I get my feet wet in a few weeks, I hope I'll be better able to contribute.

Regards.

Mike

**Pull request closed without merging**
