### PR TITLE
Add holidays for New Zealand

### PR DESCRIPTION
**Pull request by tenjaa**
Hey,

I saw New Zealand was missing, so I added the statutory holidays as described in the law.
Wikipedia summarizes them also pretty nice.

While writing this, I just saw that DAY_AFTER_NEW_YEAR and WAITANGI are unique, so I will add some translations for them.

And I copied from gb as you can see.. Will fix it too

Please tell me if I missend anything!

References:
http://www.legislation.govt.nz/act/public/2003/0129/latest/DLM237120.html#DLM237120
https://en.wikipedia.org/wiki/Public_holidays_in_New_Zealand

### CODE REVIEW

**Comment by tenjaa** [comment]
Everything I saw should be fixed.

Waitangi Day is never translated if you look through Wikipedia or the rest of the internet. So I left it as it is in every language.

Would be cool to get some feedback :)

**Comment by svendiedrichsen** [comment]
@tenjaa As far as I can tell it looks very good. Thank you very much.

**Comment by tenjaa** [comment]
Cool! 👍 

Do you have an idea when to release the next version and we can expect these changes on maven central?

**Comment by svendiedrichsen** [comment]
I had no plans but I will do it any day soon now.

**Comment by svendiedrichsen** [comment]
0.5.3 is released. Have fun.

**Pull request merged**
